// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using BlazorServerTemplate.Models.FoundationTS;

namespace BlazorServerTemplate.Data
{
    public partial class FoundationTSDbContext : DbContext
    {
        public FoundationTSDbContext()
        {
        }

        public FoundationTSDbContext(DbContextOptions<FoundationTSDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Settings> Settings { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Data Source=MasterDataTstDb;Initial Catalog=FoundationTS;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Settings>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.MatterDateLimit).HasColumnType("datetime");

                entity.Property(e => e.TimeEntryBeginDate).HasColumnType("datetime");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}